aiortc/codecs/vpx.py
I think this is correct. This prevents the `o_buf` array being resized. It appears that `i_stride` is usually bigger than `o_stride` so the slices were mismatched and `o_buf` was being resized.
=> don't resize o_buf in VpXDecoder (fixes #10)

aiortc/__init__.py, aiortc/rtcconfiguration.py, aiortc/rtcicetransport.py, aiortc/rtcpeerconnection.py, aiortc/utils.py
Closes #13 
Limitation: see https://github.com/jlaine/aioice/issues/3
- do not support multiples stun or turn server, the first of each is used
- do not support stuns or turns, it is ignored
- only support udp as transport to turn
- only support "password" credentials to turn
TODO:
- write a exemple
- write tests
=> WIP - Add iceServers support at RTCConfiguration

setup.py
I tried examples/videostream-cli. but I fail execute.
```
$ python cli.py offer
Traceback (most recent call last):
File "cli.py", line 10, in <module>
from aiortc.contrib.media import frame_from_bgr, frame_to_bgr
ModuleNotFoundError: No module named 'aiortc.contrib'
```
Is it necessary to add contrib to package?
```
$ python --version
Python 3.6.6
```
```
$ pip --version
pip 18.0
```
=> [setup] add package aiortc.contrib

.travis.yml, .travis/install
PyAV now requires ffmpeg >= 3.0, which Ubuntu 16.04 does not have.
=> [travis] build ffmpeg 3.2 from source

aiortc/rtcdatachannel.py, aiortc/rtcpeerconnection.py, aiortc/rtcsctptransport.py, tests/test_rtcpeerconnection.py, tests/test_rtcsctptransport.py
Hello,
this PR implements #150. I propose to change initializer of RTCDataChannel, moving argument id to RTCDataChannelParameters as it was not document anyway and it makes more sense to have it there.
This handles two new cases: negotiation out-of-band when we need to provide an id and providing custom id while keeping negotiation in-band.
=> Support negotiation out-of-band and custom channel IDs

.travis.yml, .travis/install, aiortc/rtcdtlstransport.py, docs/changelog.rst, tests/utils.py
To ensure it works as expected, add some Travis profiles:
- using Xenial's OpenSSL 1.0.2g
- using Trusty's OpenSSL 1.0.1f
=> [dtls] call SSL_CTX_set_ecdh_auto for OpenSSL 1.0.2

examples/server/index.html, examples/webcam/index.html
This fixes compatibility of html examples with iOS Safari.
Without the playsinline attribute, webkit browsers won't play the video stream, and it will remain black.
=> Add playsinline to video elems for ios compatibility

aiortc/mediastreams.py, aiortc/rtcdatachannel.py, aiortc/rtcdtlstransport.py, aiortc/rtcicetransport.py, aiortc/rtcpeerconnection.py, aiortc/rtcsctptransport.py, setup.py
EventEmitter is deprecated and will be removed in a future. Replace all usage of EventEmitter with AsyncIOEventEmitter class.
=> Replace deprecated EventEmitter with AsyncIOEventEmitter class

setup.py
Looks like when requirements for "av" module was updated, predicate for install_requires filter wasn't.
=> Set correct predicate that skip av module in case when READTHEDOCS set

src/aiortc/codecs/__init__.py, src/aiortc/codecs/h264.py, src/aiortc/codecs/vpx.py, src/aiortc/contrib/media.py, src/aiortc/contrib/signaling.py, src/aiortc/rtcdatachannel.py, src/aiortc/rtcdtlstransport.py, src/aiortc/rtcicetransport.py, src/aiortc/rtcpeerconnection.py, src/aiortc/rtcrtpparameters.py, src/aiortc/rtcrtpreceiver.py, src/aiortc/rtcrtpsender.py, src/aiortc/rtcsctptransport.py, src/aiortc/rtp.py, src/aiortc/sdp.py
The minimal python version for `aiortc` is 3.6 so we can replace all old-style formatting `%` by using f-strings which available from python 3.6.
=> Replace old-style string formatting with f-strings

src/aiortc/contrib/media.py, tests/test_contrib_media.py
This change allows for MediaRecorder to stream tracks to alsa hardware output.
=> Support alsa hardware output in MediaRecorder

.coveragerc, .travis.yml, .travis/script, mypy.ini, src/aiortc/codecs/__init__.py, src/aiortc/codecs/base.py, src/aiortc/codecs/g711.py, src/aiortc/codecs/h264.py, src/aiortc/codecs/opus.py, src/aiortc/codecs/vpx.py, src/aiortc/events.py, src/aiortc/jitterbuffer.py, src/aiortc/mediastreams.py, src/aiortc/rate.py, src/aiortc/rtcdatachannel.py, src/aiortc/rtcdtlstransport.py, src/aiortc/rtcicetransport.py, src/aiortc/rtcpeerconnection.py, src/aiortc/rtcrtpparameters.py, src/aiortc/rtcrtpreceiver.py, src/aiortc/rtcrtpsender.py, src/aiortc/rtcrtptransceiver.py, src/aiortc/rtcsctptransport.py, src/aiortc/rtp.py, src/aiortc/sdp.py, src/aiortc/stats.py
What was done in the scope of this pull request:
1. Rewrite all `type comments` into `type annotations`.
2. Edit code due to mypy errors.
There is a problem with `aiortc.rtcsctptransport:Chunk` class. In this class `body` attribute defined as an instance attribute but in delivered classes it defined using `property` due to it mypy throws an error. In order to suppress errors `# type: ignore` was used on the `body` property declaration.
Also, there is problem with `aiorc.rtcsctptransport:RTCSctpTransport`. `_send` method dynamically add attributes to `DataChunk` instance, due to it mypy throws an error, suppress them using `no_type_check` decorator.
I think we should resolve this problem in the future.
=> Add mypy job to .travis.yml

src/aiortc/contrib/media.py, tests/codecs.py, tests/test_contrib_media.py
When reading a file with multiple tracks, we must take care to only
close the container once the player thread has shut down. This thread is
only shut down once all tracks are stopped.
Fixes: #237, #274
=> [media player] only close container once all tracks are stopped

examples/apprtc/apprtc.py, examples/datachannel-cli/cli.py, examples/datachannel-filexfer/filexfer.py, examples/datachannel-vpn/vpn.py, examples/videostream-cli/cli.py, src/aiortc/contrib/signaling.py, tests/test_contrib_signaling.py
Using None as a "bye" magic value makes it impossible to ignore unknown
messages, for example empty "candidate" messages from appr.tc.
=> [signaling] add an explicit BYE object

README.rst, src/aiortc/rtcdtlstransport.py
Some distros:
- Debian Stretch (released in 2017) carries OpenSSL 1.1.0
- Ubuntu Xenial (released in 2016) carries OpenSSL 1.0.2g
=> [dtls] drop support for OpenSSL < 1.0.2

src/aiortc/rtcrtpsender.py, tests/test_rtcrtpsender.py
An exception raised by a MediaStreamTrack's `recv` method can result in a
deadlock (see #283), because RTCRtpSender._run_rtp will not set the
`__rtp_exited` event.
Catch exceptions, log them, and exit cleanly.
=> [rtp sender] ensure _run_rtp exits cleanly with buggy MediaStreamTracks

src/aiortc/contrib/media.py
self._player may have been cleared by a call to track.stop() while we
were waiting for a frame, so check it is not None before using it.
Fixes: #283
=> [media player] ensure self._player is not None before using it

src/aiortc/rate.py
self.current_bitrate must never be set to `None` otherwise the code
blows up.
Fixes: #295
=> [rate] fix crash in AimdRateControl

src/aiortc/rtcrtpsender.py
- Fixes https://github.com/aiortc/aiortc/issues/303
- In fact, it uses `self._track_id` which was unused until this PR :)
=> Fix trackId in "outbound-rtp" stats

src/aiortc/rtcsctptransport.py
Commit 3da949da659ad3e26b63903803570bd135c6235b switched to f-string,
but the "param" argument was still being passed, resulting in a logging
error.
=> [sctp] fix call to debug logging

src/aiortc/rtcdatachannel.py, src/aiortc/rtcdtlstransport.py, src/aiortc/rtcicetransport.py, src/aiortc/rtcrtpreceiver.py, src/aiortc/rtcrtpsender.py, src/aiortc/rtcsctptransport.py
Replace f-strings from `__debug_log` function call.
This pull request related to #262.
=> Don't use f-strings to format log messages

examples/server/server.py, examples/webcam/webcam.py
Allow a custom bind address in example scripts.
By default, the example scripts try to bind to `0.0.0.0` which triggers firewall prompts to allow on macOS.  This allows running the examples scripts on `127.0.0.1` by doing `--bind=127.0.0.1`.
=> Allow custom bind address in examples

src/aiortc/sdp.py
Hello! I was trying to stream the video feed from an iOS Swift app with GoogleWebRTC to a Python backend with aiortc, but got the following error with aiortc:
```
Traceback (most recent call last):
...
File "./app/routers/rtc_server.py", line 174, in offer
await pc.setRemoteDescription(offer)
File "/usr/local/lib/python3.8/site-packages/aiortc/rtcpeerconnection.py", line 752, in setRemoteDescription
description = sdp.SessionDescription.parse(sessionDescription.sdp)
File "/usr/local/lib/python3.8/site-packages/aiortc/sdp.py", line 435, in parse
ssrc_attr, ssrc_value = ssrc_desc.split(":")
ValueError: too many values to unpack (expected 2)
```
After inspecting the local SDP from the Swift client that is sent to aiortc, I saw this at the bottom:
```
a=ssrc-group:FID 4290189036 2679013598 …
```
=> Support srcc id/label value with a colon

src/aiortc/codecs/h264.py
fixes a small typo in the variable name
=> h264: s/nulu/nalu

docs/changelog.rst, src/aiortc/rtcpeerconnection.py
Now that we support mDNS candidates, adding remote candidates can take some
time due to mDNS lookups. As we prune some transports due to bundling,
defer adding remote candidates until after pruning has taken place. We can
also add the candidates in parallel for the different transports.
=> [ice] defer and parallelise adding remote candidates

src/aiortc/rtcdtlstransport.py, tests/test_rtcdtlstransport.py
Correctly route RTP packets when several media sections use the same
payload types.
Fixes: #382
=> [dtls] correctly route RTP packets for overlapping payload types

src/aiortc/jitterbuffer.py, src/aiortc/rtcrtpreceiver.py, tests/test_jitterbuffer.py, tests/test_rtcrtpreceiver.py
Hi,
I've prepared a fix that may interest a lot of people having picture lost issues. I discovered that a big part of those issues might be related with a bad implementation of a jitter buffer that is used for collecting RTP packets before they are passed to the appropriate decoding function. You see, each of the RTP packets sent by a browser (sender) has a packet number that is used to properly group the packets into video frames on the receiver side. In theory those packet numbers should be unique, in practice however they are limited by the unsigned short int size which is 65535. Unfortunately the aiortc jitter buffer implementation did not handle the packet numbering return from 65535 to 0 correctly, causing the jitter buffer to be purged and the video signal to be lost or at least …
=> Jitterbuffer fix + basic send PLI implementation

docs/conf.py, src/aiortc/__init__.py
It can lead to threading deadlocks, for instance avcodec_open2() hangs
with the h264_omx encoder.
=> [logging] disable PyAV logging infrastructure

src/aiortc/codecs/h264.py, stubs/av/__init__.pyi, tests/test_h264.py
On devices such as Raspberry Pi 4 we can leverage the
hardware-accelerated h264_omx encoder. Use it when possible.
=> [h264] use hardware-accelerated h264_omx when available

.github/workflows/tests.yml, .gitignore, setup.py
When installing editable option, enables option to install aiohttp and websockets to be able to run all tests local.
Update gitignore to exclude venvs
=> [Develop] Settings option for dev in setup and update  gitignore

examples/webcam/README.rst
Fix run instruction for playing from a media file: `server.py` to `webcam.py`
=> Fix webcam.py example run instruction

src/aiortc/codecs/h264.py, tests/test_h264.py
In profiling performance of #559, I noticed that a ton of time is spent in `_split_bitstream`. So I set out to speed it up. In my test case (passing through un-transcoded h264 1080p), it's now 280x faster than it was. I think it's also a lot easier to read.
Here's what I'm using to profile
```
python -m cProfile -o out.profile webcam.py
snakeviz -s -H 0.0.0.0 out.profile
```
=> Performance optimization for `_split_bitstream`

src/aiortc/contrib/media.py, tests/test_contrib_media.py
Support for unbuffered RelayStreamTrack, to ensure no delay between the original track and relayed track
=> [MediaRelay] Add support for unbuffered to MediaRelay

src/aiortc/contrib/media.py, tests/test_contrib_media.py
e.g., `player = MediaPlayer("foo.mp3", loop=True)` results in continuous playback. This is useful for bots and other sorts of testing.
=> Add support for looping to MediaPlayer

src/aiortc/rtcrtpreceiver.py, src/aiortc/rtcrtpsender.py, src/aiortc/rtp.py, tests/test_rtcrtpreceiver.py
We only keep track of the latest missing packets, it makes no sense to trigger
retransmission on older packets.
=> [rtcp] limit size of NACK reports (fixes: #584)

examples/webcam/README.rst
Hi and thank you for this great library.
As stated in the PR title, I noticed `opencv-python` is not needed to run the `webcam` example, right?
(I figured this small documentation change does not warrant to open an issue and went ahead with this PR.)
=> webcam example does not need OpenCV

src/aiortc/rtcicetransport.py, tests/test_rtcicetransport.py
I am using private stun/turn servers (e.g. Twilio). I noticed that stun url is not according with regex: `stun:global.stun.twilio.com:3478?transport=udp`. This PR is a suggestion to fix this behavior. Follow [Twilio docs for more detail](https://www.twilio.com/docs/stun-turn).
=> fix: adjusting regex for stun url

src/aiortc/codecs/base.py, src/aiortc/codecs/h264.py, src/aiortc/contrib/media.py, src/aiortc/mediastreams.py, src/aiortc/rtcrtpsender.py, tests/codecs.py, tests/test_contrib_media.py, tests/test_g711.py, tests/test_h264.py, tests/test_mediastreams.py, tests/test_opus.py, tests/test_rtcrtpsender.py, tests/test_vpx.py
I've tested `janus` example. However, I noticed that always transcode process happens, even though input codec is the same of output. I checked cpu processing consumption with transcode is ~60%.
In this PR I add an option in example that transcode does not happens. With this, cpu processing reduce to ~3% and has the same visual result. Also, latency reduce ~1.5s for video in Full HD (`1920x1080`). In this implementation, `native media player` uses h264 codec.
=> feat: creating media player that works without transcoding

setup.py, src/aiortc/rtcdtlstransport.py, tests/test_rtcdtlstransport.py
Until now we used a mix of `crytography` and direct calls to the OpenSSL bindings, which eventually broke. We now try to use only PyOpenSSL's Python API, with the exception of DTLS timeout handling which is not yet exposed by PyOpenSSL.
=> [dtls] Use PyOpenSSL's API instead of low-level APIs

src/aiortc/rtcsctptransport.py
Instead of waiting for the next reception confirmation / empty in-flight queue Fixes aiortc#776, fixes aiortc#547
Superseeds #777
In my opinion, this is the correct way to fix the datachannel latency problems.
Without this modification, sending messages appends them to the buffer, but does not transmit them if Timer 3 `_t3_handle` is active (aka. there currently are other messages in-flight).  
`_transmit` will only get called once a reception confirmation for older messages is received.
As far as I understand it, `_t3_handle` timer is meant to handle abortion & retransmits of non-acknowledged data chunks and NOT meant to lock down transmission of data.
`_transmit()` internally handles the maximum amount of in-flight packages and if that overflows, the `_outbound_queue` will not get …
=> Always try to transmit data messages immediately. Fixes #776 and #547

src/aiortc/codecs/h264.py, tests/test_h264.py
The `force_keyframe` parameter was ignored in the `_encode_frame()` method in `h264.py`
This change sets the picture type to `I` when `force_keyframe` is `True`
=> Implement force_keyframe parameter in h264

setup.py, src/aiortc/rtcdtlstransport.py
Support for DTLS timeouts was contributed upstream in PR https://github.com/pyca/pyopenssl/pull/1180 which was released in version 23.1.0, so we can remove our local implementation.
=> [package] Use pyOpenSSL >= 23.1.0 which supports DTLS timeouts

setup.py
This removes the dependency on `netifaces` (which is unmaintained) in favour of `ifaddr` (which does not require binary wheels). It also fixes some spurious state transitions due to checks being run twice.
=> [package] Depend on aioice 0.9.x

src/aiortc/contrib/media.py
In my test scenario:
```python3
import os                                                                                                                                                                                                                         
import logging                                                                                                                                                                                                                    
import asyncio                                                                                                                                                                                                                    
from aiortc.contrib.media import MediaPlayer, MediaRecorder …
```
=> add pulseaudio support to Mediarecorder

scripts/fetch-vendor.json
Upgrade:
- opus to version 1.4
- vpx to version 1.13.1 to fix CVE-2023-5217
=> Update binary opus / vpx codecs for wheels

src/aiortc/contrib/media.py
Mutable objects must not be used as default values of arguments: https://stackoverflow.com/q/26320899/13103190
=> Fix src/aiortc/contrib/media.py not to use mutable object constructors as default values of method arguments

src/aiortc/__init__.py
Missing AudioStreamTrack in __init__.py , which makes this class impossible to import
=> Add AudioStreamTrack in __init__.py

pyproject.toml, src/aiortc/rtcdtlstransport.py
As of Python 3.12, `datetime.datetime.utcnow()` is deprecated in favour of passing a timezone to `datetime.datetime.now()`. `cryptography` has also made their `datetime` handling timezone-aware so adapt to the new API.
=> Fix `utcnow()` and `not_valid_after()` deprecation warnings

src/aiortc/rtcdtlstransport.py
Fix #956 
The current DTLS cipher suite setting is `HIGH:!CAMELLIA:!aNULL` , in which case the Client Hello fragmentation occurs.
Therefore, if a library that does not support the Client Hello fragmentation, such as Mbed TLS, is used, the handshake will fail.
This problem can be solved by aligning the cipher suite to the browser and reducing the number of cipher suites.
|<img width="1077" alt="before" src="https://github.com/aiortc/aiortc/assets/18162391/527ece9e-62bd-42fa-bfa1-a30fac9ece2b">|<img width="953" alt="after" src="https://github.com/aiortc/aiortc/assets/18162391/17a31d58-ab79-4360-8147-35f810b2198b">|
|:--:|:--:|
|before|after|
In my environment, the number of cipher suites sent by Client Hello is 12, as shown below, and I checked that fragmentation does not occur.
=> Update DTLS cipher list

pyproject.toml, src/aiortc/rtcdtlstransport.py
This allows us to ensure GCM is available when installing `pylibsrtp` from binary wheels.
=> Bump required pylibsrtp version to 0.10.0

src/aiortc/rtcpeerconnection.py, tests/test_rtcicetransport.py, tests/test_rtcpeerconnection.py
When the remote peer closes the peer connection, API users need to wait until the ICE consent expires for the peer connection to move to the "closed" state.
However, we will usually receive a DTLS close_notify immediately from the remote peer. If all DTLS transports are closed, shutdown the peer connection.
Fixes: #934
=> If all DTLS transports are closed, close the peer connection

src/aiortc/rtcrtpsender.py
Once an `RTCRtpSender` stops, free the encoder as it may consume a considerable amount of memory.
Fixes: #925
=> Free encoder when RTCRtpSender finishes

.github/workflows/tests.yml
We do not run the full test suite on every wheel, as it would take too long but at least check the `aiortc` module can be imported.
=> Add a minimal smoke test for binary wheels

src/aiortc/rtcpeerconnection.py, src/aiortc/rtcrtpreceiver.py, src/aiortc/rtcrtpsender.py, src/aiortc/rtcrtptransceiver.py, tests/test_rtcrtpreceiver.py, tests/test_rtcrtpsender.py
Fixes #1053 
Enable or disable them based on the negotiated direction.
This avoids RTCRtpSender sending RTP and RTCRtpReceiver processing incoming RTP if disabled.
=> enable|disable RTCRtpSender and RTCRtpReceiver

.github/workflows/tests.yml
We can no longer use `macos-latest` for both arm64 and x86_64:
- For arm64 use macos-14.
- For x86_64 use macos-13.
=> Fix runners for building macOs wheels

src/aiortc/rtcpeerconnection.py, tests/test_rtcpeerconnection.py
RFC 8842 updated RFC 5763 to allow a differt setup attribute than
actpass
in offers which allows for more control of the DTLS role.
See https://issues.webrtc.org/issues/42223106 for additional details
Fixes #1087
=> Implement handling of non-actpass setup in offers

examples/datachannel-filexfer/filexfer.py
The example "worked" due to a global variable, but this was not the desired code.
Thanks to @angererc for spotting this!
=> Fix a typo in `filexfer` example (fixes: #1083)

src/aiortc/codecs/g711.py, src/aiortc/codecs/opus.py, src/aiortc/rtcrtpsender.py, tests/codecs.py, tests/test_g711.py, tests/test_opus.py
The `audioop` module is deprecated and will be removed in Python 3.13, so use PyAV's codecs instead.
=> Stop using deprecated `audioop` for G711 and Opus

pyproject.toml
The API remains compatible, so allow more recent versions of PyAV.
=> Allow using PyAV 12.x

.github/workflows/tests.yml, pyproject.toml, setup.py, src/aiortc/contrib/signaling.py
Adds support for Python 3.13 and drops support for EOL Python 3.8.
Feel free to edit or close if someone else is already working on this. I know this was unsolicited, but I was testing aiortc in Python 3.13 anyways and figured I'd share the changes.
There were two substantive changes:
1. Increase the upper limit for PyAV to support v13. This did cause an assertion in one test case to fail (`test_encoder_large`), but as far as I can tell there is no reason that the length of the payloads in that test must be one (nothing in the git blame indicated that either).
2. In Python 3.13, asyncio Unix sockets are removed when the server is closed so the explicit unlink needs to be skipped.
=> Add support for Python 3.13

src/aiortc/rtcrtpsender.py
to avoid the wraparound issue described by
https://chromiumdash.appspot.com/commit/13b327b05fa3788b4daa9c3463e13282824cb320
=> Choose RTP sequence numbers in the lower half of 2**16

.github/workflows/tests.yml
The CI setup using qemu for aarch64 seems highly unstable, with segfaults which are unrelated to aiortc. Until the situation stabilises, stop building wheels for Linux/aarch64.
=> Stop building wheels for Linux/aarch64

src/aiortc/rtcdtlstransport.py, tests/test_rtcdtlstransport.py
We now support SHA-256, SHA-384 and SHA-512 certificate fingerprints:
- We generate fingerprints for all supported algorithms.
- When checking fingerprints, we verify there is at least one supported algorithm, and that all supported fingerprints match.
=> Add support for sha-384 and sha-512 certificate fingerprints

src/aiortc/contrib/media.py, tests/test_contrib_media.py
Use `libopus` if the output format as `ogg`. That's a pretty important case as WebRTC audio streams are usually opus streams.
=> Set correct codec for ogg output

src/aiortc/rtcrtpsender.py
We used `del` to forcibly drop the reference to the encoder and allow it to be garbage collected. However it also means that the `RTCRtpSender` no longer has an `__encoder` attribute from then on. We can encounter a race condition during shutdown where we receive an RTCP packet, which causes access to the removed `__encoder` attribute.
Instead, just set the `__encoder` attribute back to `None`, as when the `RTCPRtpSender` was constructed.
=> Be more cautious when releasing `RTCRtpSender`'s encoder (fixes: #1124)

.github/workflows/tests.yml
GitHub actions now features native `aarch64` runners, so use them to build our wheels. We bump the Python version to 3.11 as `cibuildwheel` will soon require it.
=> Build aarch64 wheels without qemu emulation

tests/test_h264.py
The exact number of payloads produced on encoding seems to depend on the FFmpeg/libx264 versions, and possibly even the platform.
=> Relax h264 encoder test (fixes: #1166)

src/aiortc/codecs/h264.py, tests/test_contrib_media.py
The `AVError` alias to `FFmpegError` is gone in PyAV 14.
=> Use `av.FFmpegError` instead of `av.AVError`

src/aiortc/codecs/h264.py, tests/test_h264.py
The `h264_omx` codec was used to support hardware accelerated encoding on Raspberry Pi, but it hasn't been shipped with Raspbian for several releases.
=> Drop support for deprecated `h264_omx`

src/aiortc/__init__.py
When implementing custom media tracks we need to be able to raise `MediaStreamError`.
=> Expose the `MediaStreamError` exception

src/aiortc/rtcrtpreceiver.py
https://github.com/aiortc/aiortc/issues/1258#issuecomment-2679917663
Issue: ValueError: No decoder found for MIME type video/rtx
Description
A ValueError is being raised in the decoder_worker function due to the absence of a decoder for the MIME type video/rtx. This issue occurs when handling RTP packets in the RTCRtpReceiver class.
Description
A ValueError is being raised in the decoder_worker function due to the absence of a decoder for the MIME type video/rtx. This issue occurs when handling RTP packets in the RTCRtpReceiver class. The error specifically happens when a track is added to MediaRelay.
Suggested Fix
This happens because after RTX packets are unwrapped, the codec isn't updated to the apt codec, which should be used to decode the unwrapped RTX packet.
The line 'codec = …
=> Fix: No decoder found for MIME type video/rtx retransmission

pyproject.toml, src/aiortc/rtcdtlstransport.py
pyOpenSSL is deprecating its `x509.Cert` and `x509.PKey` classes in favour of their `cryptography.x509` equivalents.
=> Manipulate x509 certificates / private keys as cryptography objects

examples/webcam/webcam.py
Clarify the fact our public API is importing from the `aiortc` module directly.
=> Import `RTCRtpSender` directly from `aiortc` in webcam example

src/aiortc/__init__.py
Nowadays PyAV's default logging configuration no longer causes deadlocks. Furthermore it is much less noisy as it suppresses FFmpeg's log messages.
=> Don't touch PyAV's logging configuration

src/aiortc/rtcpeerconnection.py, tests/test_rtcpeerconnection.py
If no break statement in the changed file, the last unmatched transceiver will get. That will cause mid order different from addtrack() order in the multiple video track situation which is counterintuitive. This commit fixes it by breaking the loop in advance.
=> Fix reversed mid

src/aiortc/rtcconfiguration.py
`RTCIceServer.urls` can be a `list[str]` as well as `str` like this:
https://github.com/aiortc/aiortc/blob/65cd5653f9cc922777b706563be7f4b0058d19c4/tests/test_rtcicetransport.py#L62-L67
as its consumer method actually takes care of the case as below:
https://github.com/aiortc/aiortc/blob/65cd5653f9cc922777b706563be7f4b0058d19c4/src/aiortc/rtcicetransport.py#L99
So this PR proposes to add the type hint for it.
=> Fix the RTCIceServer.urls typing to accept `List[str]` in addition to `str`

src/aiortc/codecs/_opus.pyi, src/aiortc/codecs/_vpx.pyi
We no longer need type hints for the `_opus` and `_vpx` CFFI modules, they are gone.
=> Drop obsolete code type hints

src/aiortc/codecs/__init__.py, src/aiortc/codecs/base.py, src/aiortc/codecs/g711.py, src/aiortc/codecs/h264.py, src/aiortc/codecs/opus.py, src/aiortc/codecs/vpx.py, src/aiortc/contrib/media.py, src/aiortc/jitterbuffer.py, src/aiortc/mediastreams.py, src/aiortc/rate.py, src/aiortc/rtcconfiguration.py, src/aiortc/rtcdtlstransport.py, src/aiortc/rtcicetransport.py, src/aiortc/rtcpeerconnection.py, src/aiortc/rtcrtpparameters.py, src/aiortc/rtcrtpreceiver.py, src/aiortc/rtcrtpsender.py, src/aiortc/rtcrtptransceiver.py, src/aiortc/rtcsctptransport.py, src/aiortc/rtp.py, src/aiortc/sdp.py, tests/test_mediastreams.py
Since we no longer support Python 3.8, we can use:
- `dict` instead of `typing.Dict`.
- `list` instead of `typing.List`.
- `set` instead of `typing.Set`.
- `tuple` instead of `typing.Tuple`
=> Stop using deprecated type hints

.github/workflows/tests.yml, src/aiortc/contrib/media.py, src/aiortc/rtcdtlstransport.py, src/aiortc/rtcrtpsender.py, tests/codecs.py, tests/test_contrib_media.py, tests/test_rtcicetransport.py, tests/test_rtcpeerconnection.py, tests/test_rtcrtpsender.py, tests/utils.py
Adding type annotations to unit tests allows `mypy` to shake out missing or incorrect type annotations in our code.
=> Add type annotations to unit tests

src/aiortc/codecs/g711.py, src/aiortc/codecs/h264.py, src/aiortc/codecs/opus.py, src/aiortc/codecs/vpx.py, src/aiortc/contrib/media.py, tests/test_contrib_media.py
PyAV 14.3.0 has narrowed the types of audio / video codec contexts.
=> Remove redundant `CodecContext` type casting

src/aiortc/rtcrtpsender.py
When the RTCRtpSender operates continuously for approximately 2 hours or longer, the octet_count in RtcpSenderInfo may overflow. This can cause the RTCP component to cease transmission, thereby disrupting the audio-video synchronization mechanism and resulting in severe desynchronization during playback at the receiver's end.
The error displayed was `__bytes exception: 'L' format requires 0 <= number <= 4294967295.`
In Chrome's WebRTC C++ implementation, octet_count is implicitly converted to the uint32_t type, effectively performing a high-bit truncation. In Python, the same logic can be achieved using `& 0xFFFFFFFF` , thereby preventing overflow issues.
=> fix: Fix the octet_count overflow issue by modifying the _run_rtcp function of the RTCRtpSender class

docs/api.rst, pyproject.toml, src/aiortc/__init__.py, src/aiortc/rtcconfiguration.py, src/aiortc/rtcicetransport.py, src/aiortc/rtcpeerconnection.py, src/aiortc/rtcrtptransceiver.py, tests/test_rtcpeerconnection.py
fixes #555
Notably this also changes the default behavior to share the same ice-ufrag/ice-pwd for all transceivers and the sctp transport, aligning with browsers.
=> implement bundlePolicy

src/aiortc/rtcpeerconnection.py, src/aiortc/rtcrtptransceiver.py, tests/test_rtcpeerconnection.py
instead accesss it via the receivers transport. This is somewhat arbitrary since senders and receivers always exist but similar to how a transceivers receiver track is always set so you can get the "transceiver kind" from it.
Also remove transceiver.transport accessor added in
https://github.com/aiortc/aiortc/pull/1229#discussion_r1938353163
=> avoid having a transceiver._transport

src/aiortc/rtcicetransport.py, tests/test_rtcicetransport.py
which has been rejected in Chrome since early 2023:
https://chromiumdash.appspot.com/commits?commit=f4d463ca875f51c26a7de0e594eb1516f3e60111
=> reject stun urls with transport set

src/aiortc/contrib/signaling.py
This will make it easier to inject a custom signalling class.
=> Create an interface for all signaling implementations

examples/server/index.html, src/aiortc/codecs/__init__.py, src/aiortc/codecs/g722.py, tests/codecs.py, tests/test_g711.py, tests/test_g722.py, tests/test_opus.py, tests/test_rtcpeerconnection.py, tests/test_rtcrtpreceiver.py, tests/test_rtcrtpsender.py
The G.722 codec is "special" because the clock rate is 8kHz even though the sampling rate is 16kHz.
=> Add support for G.722 audio

src/aiortc/codecs/vpx.py, tests/test_vpx.py
When we switched to using PyAV for VP8 encoding we dropped the logic which defined the number of threads to use for encoding. This results in using as many threads as there are CPUs:
https://github.com/FFmpeg/FFmpeg/blob/b6f84cd72acd84ba725922bd6a8967b416b2230a/libavcodec/libvpxenc.c#L1014
Restore the previous behaviour.
=> Limit the number of threads for VP8 encoding

src/aiortc/codecs/vpx.py, tests/test_vpx.py
When we switched to using PyAV for VP8 encoding, we stopped handling the case where decoding a package fails. This causes the decoding thread to stop, breaking video reception. Apply the same logic we use for H.264 decoding : if we are unable to decode a package, log a warning and return an empty list of frames.
Fixes: #1315
=> Handle VP8 decoding errors to avoid stopping the decoding thread

MANIFEST.in, pyproject.toml
We no longer use `cffi` since we don't build any C code anymore.
=> Remove references to `cffi`
