aiortc/aiortc

examples/webcam/README.rst

Fix a typo

---

setup.py
src/aiortc/events.py
src/aiortc/rtcconfiguration.py
src/aiortc/rtcdatachannel.py
src/aiortc/rtcdtlstransport.py
src/aiortc/rtcicetransport.py
src/aiortc/rtcrtpparameters.py
src/aiortc/rtcrtpreceiver.py
src/aiortc/rtcsctptransport.py
src/aiortc/rtcsessiondescription.py
src/aiortc/rtp.py
src/aiortc/sdp.py
src/aiortc/stats.py

Use dataclasses instead of attrs

---

setup.py
src/aiortc/rtcicetransport.py

[ice] use regular nomination when facing an ICE Lite peer

---

src/aiortc/rtcdtlstransport.py
src/aiortc/rtcpeerconnection.py
tests/test_rtcpeerconnection.py

The previous behaviour was to always determine the DTLS role based on
the ICE role. This was correct for ORTC, but not for WebRTC where the
role is explicitly negotiated during the SDP offer / answer.
Required for #267

[dtls] correctly negotiate DTLS role

---

src/aiortc/rtcicetransport.py
src/aiortc/rtcpeerconnection.py

[ice] take controlling role if peer is ICE Lite

---

tests/test_rtcpeerconnection.py

Let's see if we can trigger the condition described in #283.

[tests] add a test for MediaPlayer used with RTCPeerConnection

---

src/aiortc/rtcpeerconnection.py
src/aiortc/rtcrtpreceiver.py
tests/test_rtcrtpreceiver.py

[rtp receiver] add RTCRtpReceiver.track property

---

src/aiortc/rtcsctptransport.py
tests/test_rtcpeerconnection.py
tests/test_rtcsctptransport.py

[data channels] look for the lowest available stream id

---

.github/workflows/tests.yml

The issue should be fixed in version 1.4.1.

[package] unpin cibuildwheel version

---

docs/changelog.rst
examples/apprtc/apprtc.py
examples/datachannel-cli/cli.py
examples/datachannel-filexfer/filexfer.py
examples/datachannel-vpn/vpn.py
examples/videostream-cli/cli.py
src/aiortc/rtcicetransport.py
src/aiortc/rtcpeerconnection.py
tests/test_ortc.py
tests/test_rtcicetransport.py
tests/test_rtcpeerconnection.py

This will be needed to support mDNS candidates. It also matches the
JavaScript WebRTC API more closely.

[breaking] make RTCPeerConnection.addIceCandidate a coroutine

---

docs/contributing.rst
docs/examples.rst

docs master -> main

---

setup.py
src/aiortc/rtcicetransport.py
tests/test_rtcicetransport.py
tests/test_rtcpeerconnection.py

CI will fail for now as it requires a change to aioice: https://github.com/aiortc/aioice/pull/44

[ice] monitor ICE connection for close event

---

src/aiortc/codecs/__init__.py
src/aiortc/rtcrtpsender.py
src/aiortc/rtp.py
tests/test_rtcrtpreceiver.py
tests/test_rtcrtpsender.py
tests/test_rtp.py

Calculate audio energy and send in RTP header extension

---

src/aiortc/rtcrtpreceiver.py
src/aiortc/rtcrtpsender.py

Both the RTCRtpSender and RTCRtpReceiver run background tasks which need
to be shutdown when `stop()` is called. When these tasks are cancelled,
they set an `Event` to inform `stop()` that a clean shutdown has
occured.
However, if the task is cancelled before it has a chance to start,
`stop()` will hang forever. We fix this by ensuring the task was
started before cancelling it.

[rtp] fix a race condition in RTP sender/receiver shutdown

---

setup.py
src/aiortc/contrib/media.py

PyAV 9 features a refactored AudioResampler which:
- outputs a list of frames (breaking change)
- handles the duties of AudioFifo internally

[media player] adapt code for PyAV 9.x

---

src/aiortc/contrib/media.py
tests/test_contrib_media.py

PyAV always initialises output video streams to 640x480, so in order to
record a video in its initial quality we need to look at the first frame
we receive.

[media recorder] determine video size from the first frame (fixes: #183)

---

.github/workflows/tests.yml
docs/conf.py
docs/helpers.rst
setup.py
src/aiortc/rtcsctptransport.py

This should avoid ending up with broken documentation on readthedocs.

[docs] test that documentation can be built without warnings

---

examples/janus/README.rst
examples/janus/janus.py

example: updating janus example with --play-without-decoding option

---

examples/janus/README.rst

https://github.com/aiortc/aiortc/issues/725

chore: fix janus readme

---

examples/webcam/README.rst

warn users webcam.py example may not work with firefox on local network

---

src/aiortc/codecs/__init__.py

Fixes #745 
Problem identified by @eerimoq

Use unique ids for audio and video header extensions

---

pyproject.toml
src/aiortc/rtcdtlstransport.py
tests/test_rtcdtlstransport.py

This requires https://github.com/pyca/pyopenssl/pull/1279

Add support for GCM based SRTP protection profiles (fixes: #1012)

---

examples/server/client.js
examples/server/index.html
examples/webcam/client.js
examples/webcam/index.html

Allow choosing audio & video input devices in `server` example

---

pyproject.toml
src/aiortc/jitterbuffer.py
src/aiortc/rtcpeerconnection.py

`pyee` v13.0.0 was released with typing improvements for `mypy`.
https://github.com/jfhbrook/pyee/releases/tag/v13.0.0
This PR proposes to introduce it.

Fix typings around `pyee`

---

.github/workflows/tests.yml

building wheels does not make much sense until lint and tests pass

github actions: depend on lint and test for building wheels

---

src/aiortc/rtcdtlstransport.py

to make the individual steps more clear
(quite interesting that the DTLS transport has no getRemoteParameters() and hence does not store them)

Split up RTCDtlsTransport.start()
